### PR TITLE
Fix Issue for prefix indexes.

### PR DESCRIPTION
**Pull request by atapatel**
While trying to create and sync indexes with prefix it failed to created proper `alias indexes`, and also unable to close and purge old indexes. I have also created fixies for the same in jolicode/elastically. 
Reference: https://github.com/jolicode/elastically/pull/40 .

### CODE REVIEW

**Comment by jacquesbh** [comment]
Hi @atapatel,

Could provide a way to reproduce the issue please?

Thanks!

**Comment by atapatel** [comment]
Steps to reproduce.
- Extend  JoliCode\Elastically\Client client to add elastically_index_prefix options.
      JoliCode\Elastically\Client:    
        arguments:
            $config:
                url: '%env(MONSIEURBIZ_SEARCHPLUGIN_ES_HOST)%:%env(MONSIEURBIZ_SEARCHPLUGIN_ES_PORT)%/'
                username: '%env(MONSIEURBIZ_SEARCHPLUGIN_ES_USER)%'
                password: '%env(MONSIEURBIZ_SEARCHPLUGIN_ES_PASSWORD)%'
                elastically_mappings_directory: '%kernel.project_dir%/config/elasticsearch/mappings'
                elastically_index_prefix: '%env(MONSIEURBIZ_SEARCHPLUGIN_ES_PREFIX)%'
                elastically_index_class_mapping:
                    # @TODO Add it in config
                    documents-en_us: \MonsieurBiz\SyliusSearchPlugin\Model\Document\Result
                elastically_bulk_size: 100
            $logger: "@logger"
- In terminal try to populate indexes using given comamnd  bin/console monsieurbiz:search:populate --verbose
- Index will be created for elastic search but its alias is created without prefix.

**Comment by atapatel** [comment]
@jacquesbh Can you please add tag for this PR, hacktoberfest ?

**Review by maximehuran — APPROVED** [review]
SGTM

**Comment by jacquesbh** [comment]
Thank you @atapatel ! 🎉

**Comment by atapatel** [comment]
@jacquesbh Thank you so much :+1:  :)

**Pull request merged**
