### PR TITLE
Authorize PHP8.0

### PR DESCRIPTION
**Pull request by Jibbarth**
Hi ! 

I tested this plugin few days on a PHP8 project thanks to `--ignore-platform-reqs`. It works well, so I think we just have to authorize it in `composer.json`

Tell me if there is anything else to do :slightly_smiling_face:

### CODE REVIEW

**Comment by jacquesbh** [comment]
Hey @Jibbarth !

Could you update the github workflows to allow PHP 8 as well?

As you can see we run some simple tests on 7.2 and 7.3. Also we should add the missing 7.4 but it's not the subject here :p.

Thank you! Let me know if you need help about it.

J

**Comment by Jibbarth** [comment]
Hi @jacquesbh 

Thanks for the review. 

I just added 7.4 and 8.0 in the list :wink:

**Comment by jacquesbh** [comment]
I think we need to upgrade some dependencies!

Let me have a quick look!

**Review by jacquesbh — APPROVED** [review]

**Review by delyriand — APPROVED** [review]

**Comment by lanfisis** [comment]
Thanks both of you for this job

**Pull request merged**
